import { Header } from "./Header.jsx";
import { useState } from "react";
import "./2FA_verification.css";
import { useSelector } from "react-redux";
import { useVerifyOTPMutation } from "../features/api/apiSlice.js";
export const TwoFAVerification = () => {
  const [code, setCode] = useState("");
  const { isSMS, isEmail, isTOTP } = useSelector((state) => state.avatar);
  const [query, queryStatus] = useVerifyOTPMutation();
  console.log(queryStatus);
  const { error, isError, isSuccess, status } = queryStatus;
  const handleChange = (e) => {
    setCode(e.currentTarget.value);
  };
  const handleSubmit = () => {
    query({ token: code, mfa: "totp", is2FAConfig: false });
  };
  return (
    <div className="twoFA_container">
      <div className="twoFA_header">
        <Header isLogin={false} isSignup={true} />
      </div>
      <div className="flex_row_width_full_grow">
        <div className="twoFA_box">
          <h3 className="twoFA_title">Enter QDrive 2-step verification code</h3>
          {isTOTP && <p>Enter the code generated by your authenticator app.</p>}
          {isEmail && <p>Enter the code sent to your email.</p>}
          {isError && <h2>Invalid Code</h2>}
          <div className="twoFA_input_container">
            <div className="twoFA_code_container">
              <label className=" twoFA_code_label">6-digit code</label>
              <input
                value={code}
                onChange={handleChange}
                type="number"
                name="code"
                className="twoFA_input"
                autoFocus={true}
              />
            </div>
            <div className="twoFA_code_button_container">
              <button
                className={`twoFA_button ${
                  code.length === 0 ? "btn_disabled" : ""
                }`}
                disabled={code.length === 0 ? true : false}
                onClick={handleSubmit}
              >
                Enter
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
