import { createContext } from "react";
const PathContext = createContext();
const FilesUploadContext = createContext();
const trackFilesProgress = createContext();
const uploadCompleted = createContext();
const filesStatus = createContext();
const showProgress = createContext();
const WhoIsUploading = createContext();
const UploadContext = createContext();
export { PathContext, UploadContext };
